# Generated by Django 5.1.7 on 2025-12-16 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jor_app', '0002_recipe_rating_recipe_rating_count_reciperating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
