# Generated by Django 5.1.7 on 2025-12-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jor_app', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
